### ISSUE TITLE
Server should handle connect message from the client

### ISSUE THREAD

**Issue by SaurabhSakpal** [adhuri/Compel-Monitoring#3]
1. Client registers with the server with a connect message. Once the connect message is received the server should save the client in memory.

2. Also, the server should no more expect any message from the client.

**Comment by adhuri** [comment]
1. no more expect any message ? or CONNECT message?  

2 What if a client disconnects ( failure ) and comes up again and sends CONNECT message ? discard ?

**Comment by SaurabhSakpal** [comment]
1. So currently the framework waits for more messages on the tcp connection. I will close the connection once the agent is registered on the server. 

2. Part 2 is already handled :+1:
