### ISSUE TITLE
Framework to send stats from RunC containers to server

### ISSUE THREAD

**Issue by SaurabhSakpal** [adhuri/Compel-Monitoring#4]

**Comment by adhuri** [comment]
**To test this** 
1. For single stat.
 Run as sudo  

```sudo /usr/local/sbin/runc events containerId --stats```

{"type":"stats","id":"mysql1","data":{"cpu":{"usage":{"total":6708598,"percpu":[26747,6681851],"kernel":0,"user":0},"throttling":{}},"memory":{"usage":{"limit":18446744073709551615,"usage":98304,"max":655360,"failcnt":0},"swap":{"limit":0,"failcnt":0},"kernel":{"limit":18446744073709551615,"failcnt":0},"kernelTCP":{"limit":18446744073709551615,"failcnt":0},"raw":{"active_anon":4096,"active_file":0,"cache":0,"hierarchical_memory_limit":18446744073709551615,"inactive_anon":94208,"inactive_file":0,"mapped_file":0,"pgfault":768,"pgmajfault":0,"pgpgin":156,"pgpgout":132,"rss":98304,"rss_huge":0,"total_active_anon":4096,"total_active_file":0,"total_cache":0,"total_inactive_anon":94208,"total_inactive_file":0,"total_mapped_file":0,"total_pgfault":768,"total_pgmajfault":0,"total_pgpgin":156,"total_pgpgout":132,"total_rss":98304,"total_rss_huge":0,"total_unevictable":0,"total_writeback":0,"unevictable":0,"writeback":0}},"pids":{},"blkio":{},"hugetlb":{"2MB":{"failcnt":0}}}}


2. For continuous stats

```sudo runc events containerId  --interval 1s```

**Comment by SaurabhSakpal** [comment]
Currently not focusing on the data we need to send. I think you can handle that part. I am talking about the overall framework.
